//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public int Id { get; set; }
        public string AdminName { get; set; }
        public string AdminPwd { get; set; }
        public int Mobile { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
        public System.DateTime JoinTime { get; set; }
        public bool State { get; set; }
        public string AdminSex { get; set; }
        public string AdminDiscription { get; set; }
    }
}
