//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Id { get; set; }
        public string FeedbackName { get; set; }
        public Nullable<bool> FeedbackState { get; set; }
        public string FeedbackCate { get; set; }
        public string FeedbackEmail { get; set; }
        public Nullable<System.DateTime> FeedbackTime { get; set; }
    }
}
